--Primeiro exercício
CREATE TABLE AUDIT_EMPLOYEES(
    EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PHONE_NUMBER VARCHAR(50),
    HIRE_DATE DATE NOT NULL,
    JOB_ID VARCHAR(20)NOT NULL,
    SALARY DECIMAL(10,2),
    COMMISSION_PCT DECIMAL(10,2),
    MANAGER_ID INT,
    DEPARTMENT_ID INT,
    
    --NOVOS CAMPOS ADICIONADOS
    AUDIT_USER VARCHAR(30) NOT NULL,
    AUDIT_ACTION CHAR(1) NOT NULL,
    AUDIT_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL  
);


--Segundo exercício
INSERT INTO EMPLOYEES (
    EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, 
    JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID
)
VALUES (
    (SELECT MAX(EMPLOYEE_ID) + 1 FROM EMPLOYEES), 
    'Pedro', 
    'Santos',
    'rm558243@fiap.com.br',  
    '11919199191',  
    TO_DATE('2025-02-02', 'YYYY-MM-DD'),  
    'MK_REP',  
    (SELECT (MIN_SALARY + MAX_SALARY) / 2 FROM JOBS WHERE JOB_ID = 'MK_REP'),  
    NULL,  
    201, 
    20 
);


