--Primeiro exercício
CREATE TABLE AUDIT_EMPLOYEES(
    EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PHONE_NUMBER VARCHAR(50),
    HIRE_DATE DATE NOT NULL,
    JOB_ID VARCHAR(20)NOT NULL,
    SALARY DECIMAL(10,2),
    COMMISSION_PCT DECIMAL(10,2),
    MANAGER_ID INT,
    DEPARTMENT_ID INT,
    
    --NOVOS CAMPOS ADICIONADOS
    AUDIT_USER VARCHAR(30) NOT NULL,
    AUDIT_ACTION CHAR(1) NOT NULL,
    AUDIT_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL  
);


